services:
  discord-bot:
    build: 
      context: .
      dockerfile: bot/Dockerfile
    container_name: discord-bot
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - TZ=Asia/Seoul
    restart: always
    command: ["python", "-m", "bot.main"]
