services:
  discord-bot:
    build: 
      context: .
      dockerfile: bot/Dockerfile
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - TZ=Asia/Seoul
    restart: unless-stopped
    command: ["python", "-m", "bot.scheduler"]